-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               8.0.30 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping data for table lcks-skaone.capaian_pembelajarans: ~20 rows (approximately)
INSERT INTO `capaian_pembelajarans` (`id_cp`, `kode_cp`, `tingkat`, `fase`, `element`, `inisial_mp`, `nama_matapelajaran`, `nomor_urut`, `isi_cp`, `created_at`, `updated_at`) VALUES
	('cp_00001', '10-A-UM-03-E-1', '10', 'E', 'Menyimak', 'A-UM-03', 'Bahasa Indonesia', '1', 'Peserta didik mampu mengevaluasi dan mengkreasi informasi berupa gagasan, pikiran, perasaan, pandangan, arahan atau pesan yang akurat dari menyimak berbagai tipe teks dalam bentuk monolog, dialog, dan gelar wicara.', '2024-10-20 20:21:22', '2024-10-20 20:21:22'),
	('cp_00002', '10-A-UM-03-E-2', '10', 'E', 'Membaca dan Memirsa', 'A-UM-03', 'Bahasa Indonesia', '2', 'Peserta didik mampu mengevaluasi informasi berupa gagasan, pikiran, pandangan, arahan atau pesan dari berbagai tipe teks visual dan audiovisual untuk menemukan makna yang tersurat dan tersirat. Peserta didik mampu menginterpretasi informasi untuk mengungkapkan gagasan dan perasaan simpati, peduli, empati dan/atau pendapat', '2024-10-20 20:22:31', '2024-10-20 20:22:31'),
	('cp_00003', '10-A-UM-03-E-3', '10', 'E', 'Berbicara dan Mempresentasikan', 'A-UM-03', 'Bahasa Indonesia', '3', 'Peserta didik mampu mengolah dan menyajikan gagasan, pikiran, pandangan, arahan atau pesan untuk tujuan pengajuan usul, perumusan masalah, dan solusi dalam bentuk monolog, dialog, dan gelar wicara secara logis, runtut, kritis, dan kreatif. Peserta didik mampu mengkreasi ungkapan sesuai dengan norma kesopanan dalam berkomunikasi. Peserta didik mampu berkontribusi lebih aktif dalam diskusi dengan mempersiapkan materi diskusi, melaksanakan tugas dan fungsi dalam diskusi. Peserta didik mampu mengungkapkan kepedulian secara kreatif dalam bentuk teks fiksi dan nonfiksi multimodal.', '2024-10-20 20:24:07', '2024-10-20 20:24:07'),
	('cp_00004', '10-A-UM-03-E-4', '10', 'E', 'Menulis', 'A-UM-03', 'Bahasa Indonesia', '4', 'Peserta didik mampu menulis gagasan, pikiran, pandangan, arahan atau pesan tertulis untuk berbagai tujuan secara logis, kritis, dan kreatif dalam bentuk teks informasional dan/atau fiksi. Peserta didik mampu menulis teks eksposisi hasil penelitian dan teks fungsional dunia kerja.', '2024-10-20 20:24:50', '2024-10-20 20:24:50'),
	('cp_00005', '11-A-UM-03-E-1', '11', 'E', 'Menyimak', 'A-UM-03', 'Bahasa Indonesia', '1', 'Peserta didik mampu mengevaluasi berbagai gagasan, pikiran, perasaan, pandangan, arahan atau pesan berdasarkan kaidah logika berpikir dari menyimak berbagai tipe teks dalam bentuk monolog, dialog, dan gelar wicara. Peserta didik mampu mengkreasi dan mengapresiasi gagasan dan pendapat untuk menanggapi teks yang disimak.', '2024-10-20 20:39:46', '2024-10-20 20:39:46'),
	('cp_00006', '11-A-UM-03-E-2', '11', 'E', 'Membaca dan Memirsa', 'A-UM-03', 'Bahasa Indonesia', '2', 'Peserta didik mampu mengevaluasi informasi berupa gagasan, pikiran, perasaan, pandangan, arahan atau pesan berdasarkan kaidah logika berpikir dari membaca berbagai tipe teks di media cetak dan elektronik. Peserta didik mampu mengapresiasi teks fiksi dan nonfiksi. Peserta didik mampu mengevaluasi dan merefleksi gagasan dan pandangan berdasarkan kaidah logika berpikir dari membaca berbagai tipe teks di media cetak dan elektronik. Peserta didik mampu mengapresiasi berbagai tipe teks. Peserta didik mampu mengaitkan isi teks dengan hal lain di luar teks.', '2024-10-20 20:40:24', '2024-10-20 20:40:24'),
	('cp_00007', '11-A-UM-03-E-3', '11', 'E', 'Berbicara dan Mempresentasikan', 'A-UM-03', 'Bahasa Indonesia', '3', 'Peserta didik mampu menyajikan gagasan, pikiran, perasaan, pandangan, arahan atau pesan dan kreativitas dalam berbahasa dalam bentuk monolog, dialog, dan gelar wicara secara logis, sistematis, kritis, dan kreatif. Peserta didik mampu menyajikan karya sastra secara kreatif dan menarik. Peserta didik mampu mengkreasi teks sesuai dengan norma kesopanan dan budaya Indonesia. Peserta didik mampu menyajikan dan mempertahankan hasil penelitian, serta menyimpulkan masukan dari mitra diskusi.', '2024-10-20 20:41:10', '2024-10-20 20:41:10'),
	('cp_00008', '11-A-UM-03-E-4', '11', 'E', 'Menulis', 'A-UM-03', 'Bahasa Indonesia', '4', 'Peserta didik mampu menulis gagasan, pikiran, pandangan, pengetahuan metakognisi untuk berbagai tujuan secara logis, kritis, dan kreatif. Peserta didik mampu menulis berbagai jenis karya sastra. Peserta didik mampu menulis teks refleksi diri. Peserta didik mampu menulis hasil penelitian, teks fungsional dunia kerja, dan pengembangan studi lanjut. Peserta didik mampu menerbitkan tulisan hasil karyanya di media cetak, elektronik, dan/atau digital.', '2024-10-20 20:41:54', '2024-10-20 20:41:54'),
	('cp_00009', '12-A-UM-03-F-1', '12', 'F', 'Menyimak', 'A-UM-03', 'Bahasa Indonesia', '1', 'Peserta didik mampu mengevaluasi berbagai gagasan, pikiran, perasaan, pandangan, arahan atau pesan berdasarkan kaidah logika berpikir dari menyimak berbagai tipe teks dalam bentuk monolog, dialog, dan gelar wicara. Peserta didik mampu mengkreasi dan mengapresiasi gagasan dan pendapat untuk menanggapi teks yang disimak.', '2024-10-20 20:42:36', '2024-10-20 20:42:36'),
	('cp_00010', '12-A-UM-03-F-2', '12', 'F', 'Membaca dan Memirsa', 'A-UM-03', 'Bahasa Indonesia', '2', 'Peserta didik mampu mengevaluasi informasi berupa gagasan, pikiran, perasaan, pandangan, arahan atau pesan berdasarkan kaidah logika berpikir dari membaca berbagai tipe teks di media cetak dan elektronik. Peserta didik mampu mengapresiasi teks fiksi dan nonfiksi. Peserta didik mampu mengevaluasi dan merefleksi gagasan dan pandangan berdasarkan kaidah logika berpikir dari membaca berbagai tipe teks di media cetak dan elektronik. Peserta didik mampu mengapresiasi berbagai tipe teks. Peserta didik mampu mengaitkan isi teks dengan hal lain di luar teks.', '2024-10-20 20:43:04', '2024-10-20 20:43:04'),
	('cp_00011', '12-A-UM-03-F-3', '12', 'F', 'Berbicara dan Mempresentasikan', 'A-UM-03', 'Bahasa Indonesia', '3', 'Peserta didik mampu menyajikan gagasan, pikiran, perasaan, pandangan, arahan atau pesan dan kreativitas dalam berbahasa dalam bentuk monolog, dialog, dan gelar wicara secara logis, sistematis, kritis, dan kreatif. Peserta didik mampu menyajikan karya sastra secara kreatif dan menarik. Peserta didik mampu mengkreasi teks sesuai dengan norma kesopanan dan budaya Indonesia. Peserta didik mampu menyajikan dan mempertahankan hasil penelitian, serta menyimpulkan masukan dari mitra diskusi.', '2024-10-20 20:43:39', '2024-10-20 20:43:39'),
	('cp_00012', '12-A-UM-03-F-4', '12', 'F', 'Menulis', 'A-UM-03', 'Bahasa Indonesia', '4', 'Peserta didik mampu menulis gagasan, pikiran, pandangan, pengetahuan metakognisi untuk berbagai tujuan secara logis, kritis, dan kreatif. Peserta didik mampu menulis berbagai jenis karya sastra. Peserta didik mampu menulis teks refleksi diri. Peserta didik mampu menulis hasil penelitian, teks fungsional dunia kerja, dan pengembangan studi lanjut. Peserta didik mampu menerbitkan tulisan hasil karyanya di media cetak, elektronik, dan/atau digital', '2024-10-20 20:44:05', '2024-10-20 20:44:05'),
	('cp_00013', '10-A-UM-04-E-1', '10', 'E', 'Keterampilan Gerak', 'A-UM-04', 'Pendidikan Jasmani, Olahraga, dan Kesehatan', '1', 'Pada akhir fase E peserta didik dapat menunjukkan kemampuan dalam mempraktikkan hasil evaluasi penerapan keterampilan gerak berupa permainan dan olahraga, aktivitas senam, aktivitas gerak berirama, dan aktivitas permainan dan olahraga air (kondisional) secara matang pada permainan, aktivitas jasmani lainnya, dan kehidupan nyata sehari-hari.', '2024-10-20 21:08:47', '2024-10-20 21:08:47'),
	('cp_00014', '10-A-UM-04-E-2', '10', 'E', 'Pengetahuan Gerak', 'A-UM-04', 'Pendidikan Jasmani, Olahraga, dan Kesehatan', '2', 'Pada akhir fase E peserta didik dapat mengevaluasi fakta, konsep, prinsip, dan prosedur dalam melakukan evaluasi penerapan keterampilan gerak berupa permainan dan olahraga, aktivitas senam, aktivitas gerak berirama, dan aktivitas permainan dan olahraga air (kondisional) pada permainan, aktivitas jasmani lainnya, dan kehidupan nyata seharihari.', '2024-10-20 21:09:35', '2024-10-20 21:09:35'),
	('cp_00015', '10-A-UM-04-E-3', '10', 'E', 'Pemanfaatan Gerak', 'A-UM-04', 'Pendidikan Jasmani, Olahraga, dan Kesehatan', '3', 'Pada akhir fase E peserta didik dapat mengevaluasi fakta, konsep, prinsip, dan prosedur dan mempraktikkan latihan pengembangan kebugaran jasmani terkait kesehatan (physicsl fittness related health) dan kebugaran jasmani terkait keterampilan (physical fittness related skills), berdasarkan prinsip latihan (Frequency, Intensity, Time, Type/FITT) untuk mendapatkan kebugaran dengan status baik. Peserta didik juga dapat menunjukkan kemampuan dalam mengembangkan pola perilaku hidup sehat berupa penerapan konsep dan prinsip pergaulan sehat antar remaja dan orang lain di sekitarnya', '2024-10-20 21:10:06', '2024-10-20 21:10:06'),
	('cp_00016', '10-A-UM-04-E-4', '10', 'E', 'Pengembangan Karakter dan Internalisasi Nilai- nilai Gerak', 'A-UM-04', 'Pendidikan Jasmani, Olahraga, dan Kesehatan', '4', 'Pada akhir fase E peserta didik mengembangkan tanggung jawab sosialnya dalam kelompok kecil untuk melakukan perubahan positif, menunjukkan etika yang baik, saling menghormati, dan mengambil bagian dalam kerja kelompok pada aktivitas jasmani atau kegiatan sosial lainnya. Peserta didik juga dapat menumbuhkembangkan cara menghadapi tantangan dalam aktivitas jasmani.', '2024-10-20 21:10:36', '2024-10-20 21:10:36'),
	('cp_00017', '11-A-UM-04-E-1', '11', 'E', 'Keterampilan Gerak', 'A-UM-04', 'Pendidikan Jasmani, Olahraga, dan Kesehatan', '1', 'Pada akhir fase ini peserta didik dapat menunjukkan kemampuan dalam mempraktikkan hasil rancangan aktivitas penerapan keterampilan gerak berupa permainan dan olahraga, aktivitas senam, aktivitas gerak berirama, dan aktivitas permainan dan olahraga air (kondisional) dengan berbagai bentuk taktik dan strategi.', '2024-10-20 21:13:49', '2024-10-20 21:13:49'),
	('cp_00018', '11-A-UM-04-E-2', '11', 'E', 'Pengetahuan Gerak', 'A-UM-04', 'Pendidikan Jasmani, Olahraga, dan Kesehatan', '2', 'Pada akhir fase ini peserta didik dapat merancang prosedur, strategi, dan taktik, terkait dengan aktivitas penerapan keterampilan gerak berupa permainan dan olahraga, aktivitas senam, aktivitas gerak berirama, dan aktivitas permainan dan olahraga air (kondisional).', '2024-10-20 21:14:17', '2024-10-20 21:14:17'),
	('cp_00019', '11-A-UM-04-E-3', '11', 'E', 'Pemanfaatan Gerak', 'A-UM-04', 'Pendidikan Jasmani, Olahraga, dan Kesehatan', '3', 'Pada akhir fase ini peserta didik dapat merancang dan mempraktikkan program latihan pengembangan kebugaran jasmani terkait kesehatan (physicsl fittness related health) dan kebugaran jasmani terkait keterampilan (physicsl fittness related skills) secara sederhana serta penggunaan instrumen pengukurannya, untuk mendapatkan kebugaran dengan status baik. Peserta didik juga dapat menganalisis bahaya, cara penularan, dan cara pencegahan HIV/AIDS, serta menganalisis langkah-langkah melindungi diri dan orang lain dari Penyakit Menular Seksual (PMS).', '2024-10-20 21:15:23', '2024-10-20 21:15:23'),
	('cp_00020', '11-A-UM-04-E-4', '11', 'E', 'Pengembangan Karakter dan Internalisasi Nilai-nilai Gerak', 'A-UM-04', 'Pendidikan Jasmani, Olahraga, dan Kesehatan', '4', 'Pada akhir fase ini peserta didik dapat mengambil peran sebagai pemimpin kelompok yang lebih besar dalam aktivitas jasmani dan olahraga dengan tetap menjunjung tinggi moral dan etika. Selain itu peserta didik dapat menginisiasi pembentukan komunitas peminatan agar orang lain menjalankan etika yang baik, saling menghormati, dan mengambil bagian dalam kerja kelompok sosial lainnya. Peserta didik juga dapat memengaruhi kelompoknya dalam mengekspresikan diri melalui aktivitas jasmani.', '2024-10-20 21:16:10', '2024-10-20 21:16:10');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
